[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_solution = "75UKGqaDPWCJDVvrURPowyzNK96rgkVSJxspuWyD7cwq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/asimnecip/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
